# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425f79437d96d2ee850832fd691fc9a16527c91358e7b5aaba1acda12979a362045538a06c8ad35d98749239f812220da552d33ac4afe4be373193eb307d542f

test:
  secret_key_base: 1e40e42c5e9edf3ef994317e3e3ab29cddf2f3d427533a64eb45b899bf315950de1db5c1d74c71bd6ef8fdc5abd9b7677d0ad55c73cb69a8ca1d1a36b7c34fb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
